baseURL = 'https://synergie-asso.github.io/'
languageCode = 'en-us'
title = 'Synergie'
theme = ["ananke-custom"]
defaultcontentlanguage = "fr"



[languages]
  #[languages.en]
  #  title = "Synergie En"
  #  weight = 2
  #  contentDir = "content/en"
  [languages.fr]
    title = "Synergie Fr"
    weight = 1
    contentDir = "content/fr"


[params]
  text_color = ""
  author = ""
  favicon = "/images/synergie_logo.png"
  site_logo = "/images/synergie_logo.png"
  description = "L’Association pour la mixité et la diversité dans l'informatique"
  # custom_css = ["carousel.css"]
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  mainSections = ["events"]
  recent_posts_number = 3

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/groups/8966912/"

[[params.ananke_socials]]
name = "instagram"
url = "https://www.instagram.com/assosynergie/"

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/synergieio"

[[params.ananke_socials]]
name = "epita"
url = "https://www.epita.fr/"